[package]
name = "firewall"
version = "0.1.0"
edition = "2021"
authors = ["Jerome David <programingjd@gmail.com>"]
categories = ["web-programming::http-server"]
description = "Connection rejection abstraction"
keywords = ["firewall", "cidr", "cloudflare"]
license = "MIT"
repository = "https://github.com/programingjd/firewall"

[dependencies.rustls]
optional = true
version = "0.22"
default-features = false
features = ["ring"]

[dependencies.reqwest]
optional = true
version = "0.11"
default-features = false
features = ["rustls-tls"]

[dependencies.cidr]
optional = true
version = "0.2"
default-features = false
features = ["std"]

[features]
default = ["builder"]
builder = ["dep:cidr"]
rustls = ["dep:rustls"]

cloudflare = ["builder","dep:reqwest"]
all = ["cloudflare"]

[dev-dependencies.tokio]
version = "1.35"
default-features = false
features = ["net", "io-util", "rt-multi-thread", "macros"]

[dev-dependencies.tokio-rustls]
version = "0.25"
default-features = false
features = ["ring"]

[dev-dependencies.rcgen]
version = "0.12"
default-features = false
features = ["ring", "pem"]

[[example]]
name = "tokio_rustls"
required-features = ["rustls"]

[[example]]
name = "cloudflare"
required-features = ["cloudflare"]
